package com.edwardjones.app.common;
/* Java Code Generated by CloudFrame */ 
import com.cloudframe.app.utility.CFUtil;
import com.cloudframe.app.data.Field;
public class CONSTANTS {
public static final char[] SPACE = " ".toCharArray();
public static final char[] ZERO = "0".toCharArray();
public static final char[] SPACE_200 = CFUtil.fillSpaces(200);
public static final char[] FORMAT1016334848 = "----".toCharArray();
public static final char[] FORMAT769933041 = "ZZZ,ZZZ,ZZ9".toCharArray();
public static final char[] FORMAT_1490104077 = "---,---,--9.99".toCharArray();
public static final char[] LITERAL_1014051608 = "Open EXCEPTION FILE failed : File-Status = ".toCharArray();
public static final char[] LITERAL_1019924377 = CFUtil.pad(1100, "*** No Exceptions ****", " ",CFUtil.RIGHT_PAD);
public static final char[] LITERAL_1066450583 = "Write EXCEPTION FILE failed : File-Status = ".toCharArray();
public static final char[] LITERAL_1091059648 = "Close RUNLOG FILE failed : File-Status = ".toCharArray();
public static final char[] LITERAL_1195131089 = "Open SUMMARY FILE failed : File-Status = ".toCharArray();
public static final char[] LITERAL_1323385110 = "Open RUNLOG FILE failed : File-Status = ".toCharArray();
public static final char[] LITERAL_1352272044 = "Fetch EXCPTION_CURSOR Cursor failed : SQLCODE = ".toCharArray();
public static final char[] LITERAL_1680254125 = CFUtil.pad(1000, "-", "-",CFUtil.RIGHT_PAD);
public static final char[] LITERAL_1681395608 = "Close SUMMARY_CURSOR failed : SQLCODE = ".toCharArray();
public static final char[] LITERAL_1879447962 = "Close EXCPTION_CURSOR failed : SQLCODE = ".toCharArray();
public static final char[] LITERAL_1920531074 = "Close EXCEPTION FILE failed : File-Status = ".toCharArray();
public static final char[] LITERAL_1964633763 = "Open RUNLOG_CURSOR Cursor failed : SQLCODE = ".toCharArray();
public static final char[] LITERAL_320510168 = "Open EXCPTION_CURSOR Cursor failed : SQLCODE = ".toCharArray();
public static final char[] LITERAL_37533272 = "Write EXCEPTION Header failed : File-Status = ".toCharArray();
public static final char[] LITERAL_452817919 = "Close RUNLOG_CURSOR failed : SQLCODE = ".toCharArray();
public static final char[] LITERAL_479762895 = "Fetch RUNLOG_CURSOR Cursor failed : SQLCODE = ".toCharArray();
public static final char[] LITERAL_497856130 = "Open SUMMARY_CURSOR Cursor failed : SQLCODE = ".toCharArray();
public static final char[] LITERAL_638212377 = "Close SUMMARY FILE failed : File-Status = ".toCharArray();
public static final char[] LITERAL_715787218 = "Fetch SUMMARY_CURSOR Cursor failed : SQLCODE = ".toCharArray();
public static final char[] LITERAL_MN11_ = "-----------".toCharArray();
public static final char[] LITERAL_MN12_ = "------------".toCharArray();
public static final char[] LITERAL_MN14_ = "--------------".toCharArray();
public static final char[] LITERAL_MN20_ = "--------------------".toCharArray();
public static final char[] LITERAL_MN26_ = "--------------------------".toCharArray();
public static final char[] LITERAL_MN8_ = "--------".toCharArray();
public static final char[] LITERAL_SIZE = "SIZE".toCharArray();
public static final char[] LITERAL_TRDPB004 = "TRDPB004".toCharArray();
public static final char[] LOW_VALUE_1253878146 = Field.fillLowValue(90);
public static final char[] LOW_VALUE_1901561749 = Field.fillLowValue(1100);
public static final char[] LOW_VALUE_215751088 = Field.fillLowValue(140);
public static final char[] MODE_WRITE_ONLY_36397 = "w".toCharArray();
 
}
