  package com.cloudframe.app.process.impl;
  /* Java code generated by CloudFrame on 2024-11-23 at 12:29. */
  
  import com.cloudframe.app.progb.ProgbCtx.*;
  import com.cloudframe.app.progb.ProgbCtx;
  import com.cloudframe.app.process.Progb;
  import com.cloudframe.app.process.BaseProcess;
  import org.springframework.web.bind.annotation.GetMapping;
  import org.slf4j.Logger;
  import org.slf4j.LoggerFactory;
  import com.cloudframe.app.exception.CFException;
  import org.springframework.stereotype.Component;
  import org.springframework.web.bind.annotation.RestController;
  import com.cloudframe.app.dto.GlobalExecutorCtx;
  import com.cloudframe.app.exception.Terminate;
  import com.cloudframe.app.progb.dto.*;
  import com.cloudframe.app.progb.dto.Work;
  import com.cloudframe.app.common.CONSTANTS;
  import com.cloudframe.app.utility.CFUtil;
  
  @Component("progb")
  
  public class ProgbImpl extends CommonProcess implements Progb {
  
  Logger logger = LoggerFactory.getLogger(ProgbImpl.class);
  
  
  
  
  
  
  
  
  
  
      /**
      * process 
      * Input  : None 

      * Output :  

      * - rc                             COBOL Name: RETURN-CODE
      *
      * @throws CFException
      */
      public int process(ProgbCtx programCtx) throws Exception {
       try {
       setCodePage("1047");
            // Reset program ended flag
           programCtx.setProgramEnded(false);
//Added variable to get the output context in place.
ProcessOutCtx methodOut = programCtx.getProcessOutCtx();
          programCtx.setRc( 16);
//  cobolCode::EXIT PROGRAM
          setNotLogged(false); // no need to log, it is a normal termination
          programCtx.setProgramEnded(true);
          return programCtx.getRc();
       } catch(Exception e) {
            handleErrorCode(e);
            throw e;
       }
      
      // end of process method
      }
  
  
  
  
  
  
  
  
  }
